from .singleton import *
from .factory_method import *
from .abstract_factory import *
from .builder import *
from .prototype import *
from .adapter import *
from .decorator import *
from .facade import *
from .proxy import *
from .composite import *
from .observer import *
from .strategy import *
from .command import *
from .template_method import *
from .state import *
from .chain_of_responsibility import *
